version: "2"
services:
  mysql:
    build: ./Dockerfile/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
  centos_php:
    privileged: true
    command: /sbin/init
    build: ./Dockerfile/centos_php
    ports:
      - "80:80"
    volumes:
      - ../../html/centOS7_PHP_MYSQL:/var/www/html
    depends_on:
      - mysql    
volumes:
  db: